import "../styles/globals.css";
import type { AppProps } from "next/app";
import Navbar from "../components/Navbar/Navbar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Sergio Diaz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/sd.jpg" />
      </Head>
      <Navbar />
      <ToastContainer />
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
